compressionLevel: mixed

enableGlobalCache: false

nodeLinker: node-modules

npmAlwaysAuth: true

npmAuthToken: "${NPM_AUTH_TOKEN:-''}"

npmRegistryServer: "https://registry.npmjs.org"

yarnPath: .yarn/releases/yarn-4.11.0.cjs
